# Generated by Django 4.2.2 on 2023-06-22 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('univ', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('gpa', models.FloatField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('photo_url', models.URLField(blank=True)),
                ('experiences', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('docs', models.TextField(blank=True)),
                ('projects', models.TextField(blank=True)),
                ('accomplishments', models.TextField(blank=True)),
                ('affiliations', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('resume_url', models.URLField(blank=True)),
                ('portfolio_website', models.URLField(blank=True)),
                ('interest_note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('JobSeeker', 'Job Seeker'), ('Recruiter', 'Recruiter')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('qualification', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('responsibilities', models.TextField(blank=True)),
                ('compensation', models.CharField(max_length=255)),
                ('employer', models.ForeignKey(db_column='employer_name', on_delete=django.db.models.deletion.CASCADE, to='apps.employer', to_field='name')),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='employer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.user'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Interviewed', 'Interviewed'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Pending', max_length=255)),
                ('p1a', models.TextField(blank=True)),
                ('p2a', models.TextField(blank=True)),
                ('p3a', models.TextField(blank=True)),
                ('p4a', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.applicant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.job')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.user'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('applicant', 'job'), name='unique_application'),
        ),
    ]
